# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxpEiU4iivtJTI9eoIvmDS_f6Qm2KhLD
"""



"""# Task
Write a Python code to generate images from text prompts using a pre-trained generative model like Stable Diffusion.

## Install necessary libraries

### Subtask:
Install libraries required for image generation, such as `diffusers` and `transformers`.

**Reasoning**:
Install the necessary libraries for image generation.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install diffusers transformers

"""## Load a pre-trained model

### Subtask:
Load a pre-trained generative model (e.g., Stable Diffusion) and its corresponding tokenizer.

**Reasoning**:
Load the pre-trained Stable Diffusion model and tokenizer.
"""

from diffusers import StableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id)
print("Stable Diffusion model loaded successfully.")

"""## Generate images

### Subtask:
Use the loaded model to generate images from text prompts.

**Reasoning**:
Define a text prompt and use the loaded `pipe` object to generate an image based on the prompt, storing the result in a variable.
"""

prompt = "a photograph of an astronaut riding a horse on the moon"
image = pipe(prompt).images[0]
display(image)

"""## Display the images

### Subtask:
Display the generated images.

## Summary:

### Data Analysis Key Findings

*   The necessary libraries for image generation, `diffusers` and `transformers`, were confirmed to be already installed in the environment.
*   A Stable Diffusion model (specifically "runwayml/stable-diffusion-v1-5") was successfully loaded using the `StableDiffusionPipeline`.
*   An image was successfully generated from the text prompt "a photograph of an astronaut riding a horse on the moon" using the loaded Stable Diffusion model.

### Insights or Next Steps

*   The generated image is ready for further processing or saving.
*   Experiment with different text prompts or model parameters to explore the model's capabilities.
"""